{%set name = "textract" %}
{%set version = "1.5.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "0e73dd1679f817bf985dd08e9e8b7e34715bb116d6ec10285a9149a145c457d7" %}
{%set build_num = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - argcomplete
    - chardet
    - python-pptx >=0.5.1
    - msg-extractor
    - python-docx
    - pdfminer ==20140328
    - beautifulsoup4
    - xlrd
    - ebooklib
    - speechrecognition >=3.1.0

test:
  imports:
    - textract
    - textract.cli
    - textract.colors
    - textract.exceptions
    - textract.parsers
    - textract.parsers.audio
    - textract.parsers.csv_parser
    - textract.parsers.doc_parser
    - textract.parsers.docx_parser
    - textract.parsers.eml_parser
    - textract.parsers.epub_parser
    - textract.parsers.gif_parser
    - textract.parsers.html_parser
    - textract.parsers.image
    - textract.parsers.jpg_parser
    - textract.parsers.json_parser
    - textract.parsers.mp3_parser
    - textract.parsers.msg_parser
    - textract.parsers.odt_parser
    - textract.parsers.ogg_parser
    - textract.parsers.pdf_parser
    - textract.parsers.png_parser
    - textract.parsers.pptx_parser
    - textract.parsers.ps_parser
    - textract.parsers.rtf_parser
    - textract.parsers.tiff_parser
    - textract.parsers.txt_parser
    - textract.parsers.utils
    - textract.parsers.wav_parser
    - textract.parsers.xls_parser
    - textract.parsers.xlsx_parser

  commands:
    - textract -h

about:
  home: https://github.com/deanmalmgren/textract
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Extract text from any document. no muss. no fuss.'
  doc_url: https://textract.readthedocs.io/en/latest/
  dev_url: https://github.com/deanmalmgren/textract

extra:
  recipe-maintainers:
    - pmlandwehr
