travis:
  secure:
    BINSTAR_TOKEN: LZWW1+wMYbeMIqV1kT5kBURgnL/BOK1NdVilfK6OExA1UE9bVvfg3D7tP8wyGX/8ASTMcsBZliWCCMaVU6ixezNakx7tUFc8pRfs3fzisDclgGrXRn0RLdcM9zdrn7C/2Blc1MxVIapumiH7uE0PYhDV9/ltWrbONkT7sTHiSesZAS9cJnVnV04asamzQoLRD8Ih6njuUU8U98P1hZH1+rKnsJZS78srSAGXbktO64k78MH6NeCXeBViCfvEmfAtjwIJ0V4/mAIViiXDOjqYGHZ1DwIw8S4tc/HN3AN+p9Qbqkbxh45V8RXqMkqr3tOdmd1gdTzJDiZSSeeKbTsYvQygWs5OaAiL2dqKablUH7MS6SkykjK8s/XRrJqHbSFpLuzTj1+tnDb67EKux91TZ3bhtu7YR/NekPOzj25Tn9oiP0CTqSAWymbTIBQclfW4aXufCHYGJtpCQyb3NIVeG03wZbiepRJwqRpW8IJCzArnIorbWdXrIz1yvZ8nAZZWNSE9trq//j/IcqsMwnPysXseOTL7bm3a1UOiSduOC0wy/vo4HR+cPIzFKYxS0GzUnwnsC3Tb54ARkXrOKRjHlsY82sQ4v8ZYq51VAks5zH2o23r7Bvch66kDzys/FVoac3TRDaORt3sB1bR9KIc20k3uKdOlPxcjL9Q43VdcrXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
