travis:
  secure:
    BINSTAR_TOKEN: PNl5eNax4mSVnPiqPVF8K1Gq6hn/hdu4zhOKQqLqcFWR5wuR93CZSrCY84TveReRAAksKYn3ufNM4EdSlkAu6w3Na5UKAOvZVUiQU13lW56amHeroxlovB2KFh2JRmxHTyisdNjtYaV43Lbr5jla1iigmtU26j6IfsqHcr/aM9dUXicaox6eErObNkyWluIKX1DNAnvyATiZdwPdt4D/zakKcPaodelJI+ygKz4Jex8OvPNjz5fRrWNPjpnWcVD+8Kn8WHGsa8Xj8B5hlDvSNctP8bIzFQMHG5w4am2nKpOo8RKpoZcbje1thwQoswdq7SD+ls70ztrRDA14LV/wNESLf4ut8FRzkAGHsEAC+2ziHfTnrgLraMUMO0Nhl/ziTylhCxWpCTaJM8aYN6ok6QSWHqTuj4D1LsANESYtk6C3n6dxcJXYrbcndPJQqGWL8AJBHKQN0DsPyYCXNQMWsFfmPZuqIUaEpliCgbLdldLrS0zy54UKFxKD6HFRyYcpUAd0J/WLuFYo1G+UkovozcB+XjCeT1wOH2PHM9Mh/RY/fHYwqljjaz5il0zx99SEr2NB+U1VsmFX0aT3pUhdIh1WagkI7feQCsMUsg5HkKLmX0WG3KCDx+cw6dTqThd8niWo/Fe87YGotY5350kT1i4H/iiZTgEIlE+uaEvrMHM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
