travis:
  secure:
    BINSTAR_TOKEN: hub/Mmij4d4Op5DyCgdo47/Uuc1O7Tu5IShuX8wQfqvQu4khPmI7Biy+9oAi5dbSQWXCQnMH020x/PFaL5AyZJ2xgb2PD8XsHraICfDAN3jaVGuNrz80CsqxBSqlRSBoJrZWfrEzU1LhdgBwEhw28Wzju1wbkLaLbL8RDP6DmggYhUiZiFwoGuF2gH+PoPazu1BUQ40Ozzu/JOJzVu4M3ELamAINCzd3NxhaqwUxrYack2/LxR9ZmS3XrHxs9XG8kQJpBz9AHwCL19prEmuLRnBv2Rn5SgSfdVoBtW9qpglV0D0eaVCTvvMssbT3nuuyMWifpW4kHXJ3DrW7wQVULiRFl13+ZFtblx44XAPL9IJsfaxFSYGXCUVo8YC5Z0sRWxwis7wDX2hzr4CThMCvsf2Z3sWOs9yYw7ho33Mou/Jkzaq8dwh//MCBn1Omh3b1T5B7aSFcTAYyA8edjB68AMheR6EzPnl9NEmekTLsQIZN9/oXPFb1lkeWG/XzRilO1u53GNqAaIZsko9bDCjX5GDuC72JvAIXk5Geq3e/YLpVjqhy2r2amJRSGYFvcAX955SMg1QcpvjDe9YseoEWALhOxMi4p/oYsOruY+4seDtKql86MT/7WJCY2N+SovdHFW3hViKqJ0I+WuocImZTVK3XcblKm1gem9ecA22VlII=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
